### ISSUE TITLE
Improvement Suggestion: User friendly menus

### ISSUE THREAD

**Issue by AGuski** [JCPetrelli/pi_games#1]
To make menus a bit more user friendly and fun, consider using one of these libraries for all the menus:

https://github.com/bchao1/bullet (https://pypi.org/project/bullet/)
or
https://pypi.org/project/simple-term-menu/

**Comment by JCPetrelli** [comment]
Hi @AGuski ! Thanks for the tip, I've implemented simple term menu with commit 1d44bd143bbfd8961e7b327ad0824bc57c816193 ;)
